# Generated by Django 4.1.3 on 2022-11-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0002_remove_question_question_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_code",
            field=models.TextField(default=""),
        ),
    ]
