# Generated by Django 4.1.3 on 2022-11-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_question_question_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='textModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField()),
            ],
        ),
    ]
