# Generated by Django 4.1.3 on 2022-11-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0004_rename_question_problem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solution_code", models.TextField(default="")),
            ],
        ),
    ]
