# Generated by Django 4.1.3 on 2022-12-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0006_remove_problem_id_problem_problem_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="problem",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="topics.problem",
            ),
        ),
    ]
