# Generated by Django 4.1 on 2022-12-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_textmodel'),
        ('topics', '0006_remove_problem_id_problem_problem_id'),
    ]

    operations = [
    ]
