# Generated by Django 4.1.3 on 2022-12-01 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0009_remove_solution_problem"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="problem",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="topics.problem",
            ),
        ),
    ]
