# Generated by Django 4.1.3 on 2022-12-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0011_alter_solution_problem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solutions",
                to="topics.problem",
            ),
        ),
    ]
