# Generated by Django 4.1 on 2022-12-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_merge_20221201_2003'),
        ('topics', '0012_alter_solution_problem'),
    ]

    operations = [
    ]
