# Generated by Django 4.1 on 2022-12-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0013_merge_20221203_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='textModel',
        ),
    ]
