# Generated by Django 4.1.3 on 2022-12-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0014_delete_textmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="topic_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
