name: Django CI

on:
  push:
    branches: [ "django_front" ]
  pull_request:
    branches: [ "django_front" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Run Tests
      run: |
        python manage.py test
